import { LevelData, EntityType } from './types';
import { DEFAULT_PHYSICS, COLORS, CANVAS_HEIGHT, CANVAS_WIDTH } from './constants';

export const LEVELS: LevelData[] = [
  {
    id: 1,
    name: "INIT_SEQUENCE",
    description: "The door is locked. Access the door's properties to proceed.",
    startPos: { x: 100, y: 400 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_1',
        type: EntityType.WALL,
        name: 'FloorSegment',
        pos: { x: 0, y: 500 },
        size: { x: 800, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'door_1',
        type: EntityType.DOOR,
        name: 'SecurityGate',
        pos: { x: 600, y: 350 },
        size: { x: 40, y: 150 },
        velocity: { x: 0, y: 0 },
        color: COLORS.doorLocked,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        isLocked: true,
        description: "Standard firewall gate. Identify boolean lock parameter."
      },
      {
        id: 'exit_1',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 700, y: 400 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: false 
      },
      {
        id: 'hint_1',
        type: EntityType.TEXT,
        name: 'TutorialText',
        pos: { x: 200, y: 200 },
        size: { x: 0, y: 0 },
        velocity: { x: 0, y: 0 },
        color: COLORS.text,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        label: "CLICK OBJECTS TO INSPECT // REWRITE PROPERTIES"
      }
    ]
  },
  {
    id: 2,
    name: "GRAVITY_WELL",
    description: "The laws of physics are just variables. Lower the gravity to cross.",
    startPos: { x: 50, y: 400 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'platform_start',
        type: EntityType.WALL,
        name: 'StartPlatform',
        pos: { x: 0, y: 500 },
        size: { x: 200, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'platform_end',
        type: EntityType.WALL,
        name: 'EndPlatform',
        pos: { x: 600, y: 400 },
        size: { x: 200, y: 200 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'enemy_patrol_2',
        type: EntityType.ENEMY,
        name: 'Sentry_Bot',
        pos: { x: 650, y: 360 },
        size: { x: 30, y: 30 },
        velocity: { x: 50, y: 0 },
        color: COLORS.enemy,
        isStatic: false,
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 650, y: 360 },
        patrolEnd: { x: 750, y: 360 },
        patrolSpeed: 50,
        description: "Standard patrol unit. Avoid contact."
      },
      {
        id: 'gap_hint',
        type: EntityType.TEXT,
        name: 'SystemAlert',
        pos: { x: 300, y: 200 },
        size: { x: 0, y: 0 },
        velocity: { x: 0, y: 0 },
        color: COLORS.text,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        label: "WARNING: GAP EXCEEDS JUMP PARAMETERS"
      },
      {
        id: 'exit_2',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 700, y: 300 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
   {
    id: 3,
    name: "GHOST_WALL",
    description: "Obstacles are only real if collision is enabled.",
    startPos: { x: 50, y: 400 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_3',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 500 },
        size: { x: 800, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'impassable_wall',
        type: EntityType.WALL,
        name: 'Firewall_Heavy',
        pos: { x: 400, y: 200 },
        size: { x: 100, y: 300 },
        velocity: { x: 0, y: 0 },
        color: COLORS.enemy,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        description: "High-density data barrier. Collision enabled."
      },
      {
        id: 'turret_3',
        type: EntityType.ENEMY,
        name: 'Watcher_V1',
        pos: { x: 200, y: 100 },
        size: { x: 40, y: 40 },
        velocity: { x: 0, y: 0 },
        color: COLORS.turret,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        behavior: 'TURRET',
        fireRate: 2500,
        description: "Fixed placement turret. Monitors wall integrity."
      },
      {
        id: 'exit_3',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 700, y: 400 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 4,
    name: "FIREWALL_BREACH",
    description: "The security grid is active. Deadly hazards detected.",
    startPos: { x: 50, y: 250 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_4',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 550 },
        size: { x: 800, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'start_plat',
        type: EntityType.WALL,
        name: 'Start',
        pos: { x: 0, y: 300 },
        size: { x: 150, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'laser_1',
        type: EntityType.ENEMY,
        name: 'Laser_Grid_A',
        pos: { x: 200, y: 400 },
        size: { x: 20, y: 150 },
        velocity: { x: 0, y: 100 },
        color: COLORS.deadly,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        isDeadly: true,
        description: "Thermal barrier. Contact results in termination."
      },
      {
        id: 'laser_2',
        type: EntityType.ENEMY,
        name: 'Laser_Grid_B',
        pos: { x: 350, y: 200 },
        size: { x: 20, y: 200 },
        velocity: { x: 0, y: -100 },
        color: COLORS.deadly,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        isDeadly: true
      },
      {
        id: 'laser_3',
        type: EntityType.ENEMY,
        name: 'Laser_Grid_C',
        pos: { x: 500, y: 400 },
        size: { x: 20, y: 150 },
        velocity: { x: 0, y: 50 },
        color: COLORS.deadly,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        isDeadly: true
      },
      {
        id: 'exit_4',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 700, y: 450 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 5,
    name: "KERNEL_PANIC",
    description: "Memory block detected. Invert mass to clear the path.",
    startPos: { x: 50, y: 450 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_5',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 500 },
        size: { x: 800, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'heavy_block',
        type: EntityType.WALL,
        name: 'Data_Block_4TB',
        pos: { x: 300, y: 200 },
        size: { x: 100, y: 300 },
        velocity: { x: 0, y: 0 },
        color: COLORS.platform,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        gravityScale: 5,
        description: "Extremely heavy data cluster. Static lock engaged."
      },
      {
        id: 'drone_5',
        type: EntityType.ENEMY,
        name: 'Drone_Seeker',
        pos: { x: 450, y: 100 },
        size: { x: 30, y: 30 },
        velocity: { x: 0, y: 0 },
        color: COLORS.enemy,
        isStatic: true, 
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'TURRET',
        fireRate: 3000,
        description: "Ceiling mounted defense unit."
      },
      {
        id: 'ceiling',
        type: EntityType.WALL,
        name: 'Ceiling_Limit',
        pos: { x: 0, y: -100 },
        size: { x: 800, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'exit_5',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 600, y: 400 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 6,
    name: "BUFFER_OVERFLOW",
    description: "Verticality required. Local gravity inversion recommended.",
    startPos: { x: 50, y: 450 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_6',
        type: EntityType.WALL,
        name: 'Floor_Standard',
        pos: { x: 200, y: 550 },
        size: { x: 200, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        description: "Standard footing."
      },
      {
        id: 'start_ledge',
        type: EntityType.WALL,
        name: 'Ledge',
        pos: { x: 0, y: 500 },
        size: { x: 150, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'high_wall',
        type: EntityType.WALL,
        name: 'Firewall_Height_Limit',
        pos: { x: 450, y: 100 },
        size: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'hint_6',
        type: EntityType.TEXT,
        name: 'Hint',
        pos: { x: 100, y: 300 },
        size: { x: 0, y: 0 },
        velocity: { x: 0, y: 0 },
        color: COLORS.text,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        label: "MODIFY PLAYER GRAVITY SCALE < 0"
      },
      {
        id: 'exit_6',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 600, y: 400 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 7,
    name: "PERIMETER_DEFENSE",
    description: "Active countermeasures detected. Visibility locks engaged.",
    startPos: { x: 50, y: 450 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_7',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 550 },
        size: { x: 800, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'patrol_bot_1',
        type: EntityType.ENEMY,
        name: 'Patrol_Unit_X1',
        pos: { x: 300, y: 520 },
        size: { x: 30, y: 30 },
        velocity: { x: 100, y: 0 },
        color: COLORS.enemy,
        isStatic: false,
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 300, y: 520 },
        patrolEnd: { x: 500, y: 520 },
        patrolSpeed: 100,
        description: "Automated sentry. Movement patterns: Oscillating."
      },
      {
        id: 'turret_1',
        type: EntityType.ENEMY,
        name: 'Auto_Turret_V2',
        pos: { x: 700, y: 350 },
        size: { x: 40, y: 40 },
        velocity: { x: 0, y: 0 },
        color: COLORS.turret,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        behavior: 'TURRET',
        fireRate: 2000,
        projectileSpeed: 300,
        description: "Projectile launcher. Disable firing mechanism."
      },
      {
        id: 'secure_wall',
        type: EntityType.WALL,
        name: 'Hardened_Firewall',
        pos: { x: 500, y: 350 },
        size: { x: 50, y: 200 },
        velocity: { x: 0, y: 0 },
        color: '#475569',
        isStatic: true,
        isSolid: true,
        isVisible: true,
        isAlwaysVisible: true,
        description: "Core infrastructure. Visibility properties are read-only."
      },
      {
        id: 'platform_mid',
        type: EntityType.WALL,
        name: 'Platform',
        pos: { x: 200, y: 400 },
        size: { x: 200, y: 20 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'exit_7',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 750, y: 450 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 8,
    name: "RACE_CONDITION",
    description: "Synchronization error. Hardware cycles are too fast for human reaction.",
    startPos: { x: 50, y: 450 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_8',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 550 },
        size: { x: 800, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'crusher_1',
        type: EntityType.ENEMY,
        name: 'Piston_Fast',
        pos: { x: 250, y: 200 },
        size: { x: 80, y: 300 },
        velocity: { x: 0, y: 800 },
        color: COLORS.platform,
        isStatic: false, 
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 250, y: 200 },
        patrolEnd: { x: 250, y: 500 },
        patrolSpeed: 800,
        description: "Hydraulic crusher operating at 800Hz. Unsafe velocity."
      },
      {
        id: 'crusher_h1',
        type: EntityType.ENEMY,
        name: 'Cyber_Ram_A',
        pos: { x: 200, y: 480 },
        size: { x: 100, y: 70 },
        velocity: { x: 600, y: 0 },
        color: COLORS.deadly,
        isStatic: false,
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 200, y: 480 },
        patrolEnd: { x: 500, y: 480 },
        patrolSpeed: 600,
        description: "High-speed kinetic ram. Slow down system time to evade."
      },
      {
        id: 'crusher_h2',
        type: EntityType.ENEMY,
        name: 'Cyber_Ram_B',
        pos: { x: 400, y: 400 },
        size: { x: 100, y: 70 },
        velocity: { x: -700, y: 0 },
        color: COLORS.deadly,
        isStatic: false,
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 400, y: 400 },
        patrolEnd: { x: 700, y: 400 },
        patrolSpeed: 700
      },
      {
        id: 'safe_plat',
        type: EntityType.WALL,
        name: 'Safe_Zone',
        pos: { x: 350, y: 250 },
        size: { x: 100, y: 20 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'exit_8',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 750, y: 450 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      },
       {
        id: 'hint_8',
        type: EntityType.TEXT,
        name: 'Hint',
        pos: { x: 100, y: 200 },
        size: { x: 0, y: 0 },
        velocity: { x: 0, y: 0 },
        color: COLORS.text,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        label: "GLOBAL PROPERTY: TIME_DILATION"
      }
    ]
  },
  {
    id: 9,
    name: "ZERO_DAY_EXPLOIT",
    description: "Asset repurposing required. The payload is the transport.",
    startPos: { x: 50, y: 400 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'start_plat_9',
        type: EntityType.WALL,
        name: 'Start',
        pos: { x: 0, y: 500 },
        size: { x: 200, y: 100 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'end_plat_9',
        type: EntityType.WALL,
        name: 'End',
        pos: { x: 600, y: 400 },
        size: { x: 200, y: 200 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'transport_drone',
        type: EntityType.ENEMY,
        name: 'Payload_Carrier',
        pos: { x: 200, y: 450 },
        size: { x: 120, y: 20 },
        velocity: { x: 100, y: 0 },
        color: COLORS.enemy,
        isStatic: false,
        isSolid: true,
        isVisible: true,
        isDeadly: true,
        behavior: 'PATROL',
        patrolStart: { x: 200, y: 450 },
        patrolEnd: { x: 600, y: 250 },
        patrolSpeed: 100,
        gravityScale: 0,
        description: "High-voltage transport layer. Unsafe for contact. Reprogram to safe mode."
      },
      {
        id: 'interceptor',
        type: EntityType.ENEMY,
        name: 'Firewall_Daemon',
        pos: { x: 400, y: 100 },
        size: { x: 40, y: 40 },
        velocity: { x: 0, y: 0 },
        color: COLORS.turret,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        behavior: 'TURRET',
        fireRate: 2000,
        projectileSpeed: 300,
        description: "Aerial interceptor. Disable to ensure safe passage."
      },
      {
        id: 'hint_9',
        type: EntityType.TEXT,
        name: 'Hint',
        pos: { x: 300, y: 300 },
        size: { x: 0, y: 0 },
        velocity: { x: 0, y: 0 },
        color: COLORS.text,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        label: "RIDE THE SIGNAL"
      },
      {
        id: 'exit_9',
        type: EntityType.EXIT,
        name: 'LevelExit',
        pos: { x: 700, y: 300 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#ffffff',
        isStatic: true,
        isSolid: false,
        isVisible: true
      }
    ]
  },
  {
    id: 10,
    name: "ROOT_ACCESS",
    description: "Final security layer. Total system override required.",
    startPos: { x: 50, y: 500 },
    physics: { ...DEFAULT_PHYSICS },
    entities: [
      {
        id: 'floor_10',
        type: EntityType.WALL,
        name: 'Floor',
        pos: { x: 0, y: 550 },
        size: { x: 300, y: 50 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'door_final',
        type: EntityType.DOOR,
        name: 'Root_Gate',
        pos: { x: 300, y: 400 },
        size: { x: 40, y: 200 },
        velocity: { x: 0, y: 0 },
        color: COLORS.doorLocked,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        isLocked: true
      },
      {
        id: 'turret_final_1',
        type: EntityType.ENEMY,
        name: 'Guardian_A',
        pos: { x: 250, y: 150 },
        size: { x: 40, y: 40 },
        velocity: { x: 0, y: 0 },
        color: COLORS.turret,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        behavior: 'TURRET',
        fireRate: 1000,
        description: "Fast firing guardian."
      },
       {
        id: 'turret_final_2',
        type: EntityType.ENEMY,
        name: 'Guardian_B',
        pos: { x: 400, y: 100 },
        size: { x: 40, y: 40 },
        velocity: { x: 0, y: 0 },
        color: COLORS.turret,
        isStatic: true,
        isSolid: true,
        isVisible: true,
        behavior: 'TURRET',
        fireRate: 1200
      },
      {
        id: 'pit_laser',
        type: EntityType.ENEMY,
        name: 'Laser_Floor',
        pos: { x: 350, y: 580 },
        size: { x: 200, y: 20 },
        velocity: { x: 0, y: 0 },
        color: COLORS.deadly,
        isStatic: true,
        isSolid: false,
        isVisible: true,
        isDeadly: true
      },
      {
        id: 'float_plat',
        type: EntityType.WALL,
        name: 'Stepping_Stone',
        pos: { x: 450, y: 450 },
        size: { x: 100, y: 20 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: true
      },
      {
        id: 'exit_10',
        type: EntityType.EXIT,
        name: 'SystemCore',
        pos: { x: 700, y: 450 },
        size: { x: 50, y: 100 },
        velocity: { x: 0, y: 0 },
        color: '#00ff00',
        isStatic: true,
        isSolid: false,
        isVisible: true
      },
      {
        id: 'final_wall',
        type: EntityType.WALL,
        name: 'Final_Check',
        pos: { x: 600, y: 0 },
        size: { x: 50, y: 600 },
        velocity: { x: 0, y: 0 },
        color: COLORS.wall,
        isStatic: true,
        isSolid: true,
        isVisible: false, // Invisible wall blocking exit!
        description: "Hidden barrier. Trust nothing."
      }
    ]
  }
];